CREATE TABLE `annuncio` (
	`idannuncio` INT(11) NOT NULL AUTO_INCREMENT,
	`nazione` VARCHAR(255) NULL DEFAULT NULL,
	`regione` VARCHAR(255) NULL DEFAULT NULL,
	`provincia` VARCHAR(255) NULL DEFAULT NULL,
	`comune` VARCHAR(255) NULL DEFAULT NULL,
	`idxml` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`idannuncio`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=222
;